-- src/shared/Configuration.lua
local Configuration = {}

-- [[ CORE SETTINGS ]]
Configuration.MaxLength = 250 -- Max characters per message
Configuration.HistoryLength = 50 -- How many messages to keep in client memory

-- [[ SECURITY / FLOOD PROTECTION ]]
-- We use a Token Bucket algorithm for smooth rate limiting.
Configuration.RateLimit = {
	MaxTokens = 5,       -- Player can send 5 messages quickly
	RestoreRate = 0.5,   -- Generates 1 new message allowance every 2 seconds
	Cost = 1,            -- Each message costs 1 token
}

-- [[ VISUALS ]]
Configuration.Colors = {
	Global = Color3.fromRGB(255, 255, 255),
	Team = Color3.fromRGB(0, 170, 255),
	System = Color3.fromRGB(255, 215, 0),
	Whisper = Color3.fromRGB(120, 120, 120),
	Admin = Color3.fromRGB(255, 85, 85),
}

Configuration.Fonts = {
	Default = Enum.Font.GothamMedium,
	Bold = Enum.Font.GothamBold,
}

-- [[ CHANNELS ]]
Configuration.AutoJoinGlobal = true

-- [[ COMMAND BRIDGE ]]
-- Optional compatibility for admin scripts that listen to Roblox chat events.
Configuration.CommandBridge = {
	Enabled = true,
	ForwardAll = false, -- If true, forwards every message; otherwise only prefixes.
	Prefixes = { "/", "!", ";", ":" }, -- Add/remove prefixes as needed.
	SuppressInChat = false, -- If true, don't broadcast command-like messages.
}

-- [[ 1. TERMINOLOGY CORRECTION (The "Skid Humiliator") ]]
-- Disabled by default. If enabled, replaces "hacker" terms with humiliating alternatives.
Configuration.TerminologyCorrection = false
-- Optional: replace entire message with a random sentence if it contains hacker/cheater terms.
Configuration.SkidSentenceMode = false
Configuration.SkidSentenceKeywords = {
	"hacker",
	"hackers",
	"cheater",
	"cheaters",
	"cheat",
	"cheats",
	"cheating",
	"exploiter",
	"exploiters",
	"exploit",
	"exploiting",
}
-- Random chant burst when someone calls another player a "hacker".
Configuration.SkidChantEnabled = true
Configuration.SkidChantChance = 0.25
Configuration.SkidChantCooldown = 30
Configuration.SkidChantKeywords = { "hacker", "hackers" }
Configuration.SkidChantMessage = "If you hate cheaters and you know it clap your hands!"
Configuration.SkidChantFinalMessage = "If you hate cheaters and you know it and you really wanna show it, if you hate cheaters and you know it clap your hands!"
Configuration.SkidChantEmoji = "👏👏"
Configuration.SkidChantRounds = 3
Configuration.SkidChantDelay = 0.6
Configuration.SkidSentenceReplacements = {
	"Calling yourself a hacker doesn't make it true; your biggest exploit is the download button.",
	"You're not a hacker, you're just fast at following a YouTube tutorial.",
	"Congrats on the hacks - your copy and paste keys are exhausted.",
	"If there was a medal for downloading scripts, you'd be gold.",
	"Imagine bragging about cheats like it takes skill.",
	"Your 'hacks' are just rented confidence.",
	"Cheating isn't talent; it's just a shortcut with extra steps.",
	"Nice hacks. Even your shortcuts need a shortcut.",
	"NASA called. They want their gravity back from your ego.",
	"You're not hacking, you're just speedrunning the terms of service.",
	"Your whole skill tree is just CTRL+C and CTRL+V.",
	"Patch notes fear you. Not because you're smart - because you didn't read them.",
	"Your best combo is Alt + Tab + Download.",
	"You're the reason tutorial videos have comments like 'thanks bro'.",
	"Cheating is like microwaving a five-star meal: fast, easy, and still kinda sad.",
	"You're not a hacker, you're a demo version of confidence.",
	"That wasn't a hack, that was a bookmark.",
	"Every 'exploit' you know is a search bar away.",
	"Your cheats have more aim assist than you do.",
	"Your biggest flex is installing things without reading.",
	"404: skill not found. Did you try turning the cheats off and on again?",
	"Your KD has a null pointer exception.",
	"You're basically a walking 'sudo' prompt with no password.",
	"Cheats are just a fancy wrapper around 'I give up'.",
	"Your gameplay is a beta build with a paid patch.",
	"Stop calling it hacking - it's just downloading a RAT with extra steps.",
	"Congrats on the free malware bundle: now with bonus keylogger.",
	"Your cheat client mines more crypto than it wins fights.",
	"Installing a cheat is the fastest way to get a RAT roommate.",
	"Your 'exploit' is just a Trojan horse in a hoodie.",
	"You're running more background processes than the game.",
	"Your aimbot has better tracking than your antivirus.",
	"Cheats: because reading a stack trace is scarier than losing.",
	"Your hacks are like npm dependencies: half are malware, all are drama.",
	"Even your downloads need a patch Tuesday.",
	"Hacker hacker, little star, how I wonder where your skills are.",
	"Cheater cheater, pumpkin eater, couldn't win so bought a meter.",
	"Row, row, row your cheats, gently down the stream - when you face a fair 1v1, you uninstall in your dream.",
	"Twinkle, twinkle, fake little star, how I wonder where your skills are.",
	"Mary had a little cheat, its fleece was extra laggy; everywhere that Mary went, her antivirus was saggy.",
	"Humpty Dumpty sat on wall, Humpty Dumpty had a fall; all the cheats and all the scripts couldn't make him good at all.",
	"Old MacDonald had a cheat, E-I-E-I-nope; with a RAT rat here and a RAT rat there, enjoy that malware cope.",
	"Baa baa black cheat, have you any skill? No sir, no sir, just a toggle and a will.",
	"Jack and Jill went up the hill to fetch a scripted crown; Jack fell down and Jill got banned for toggling it around.",
	"Ring-a-ring o' roses, a pocket full of hacks; a server full of ban logs - and down goes your account.",
	"Little Miss Muffet sat on a bucket, bragging about her hacks; along came a patch and sat down beside her, and frightened her into facts.",
	"This little piggy went to the lobby, this little piggy hit 'inject'; this little piggy cried 'patch day', and this little piggy got wrecked.",
	"There was an old cheat who lived in a shoe; they had so many alts, they didn't know what to do.",
	"Hey diddle diddle, the cheat and the riddle; the script jumped over the ban; the anti-cheat laughed to see such sport, and kicked them out of the clan.",
	"London Bridge is falling down, falling down, falling down; your exploit's gone, your alts are gone, enjoy that patch around.",
	"Rock-a-bye cheater, in the treetop; when the patch hits, the cheats will stop; when the ban drops, the cheater will fall, and down will come account and all.",
	"Simple Simon met a piper, tuning cheats for fun; Simple Simon paid a fiver and got a stealer, one by one.",
	"Georgie Porgie, pudding and pie, called himself a hacker to feel fly; when the logs came out to play, Georgie Porgie ran away.",
	"Humpty Dumpty had a script, Humpty Dumpty had a fall; all the mods and all the bans couldn't save his alt at all.",
	"Mary had a little cheat, everywhere that Mary went; the anti-cheat was sure to go, and that was time well spent.",
	"Row, row, row your cheats, gently down the stream; patch day came and sank your scripts and ended your whole dream.",
	"Twinkle, twinkle, little skid, how I wonder what you did; up above the ban wave high, like a server in the sky.",
	"X and Y sitting in a tree, C-H-E-A-T-I-N-G; first comes ban, then comes tears, then comes alt accounts in fear.",
	"Hickory dickory dock, the cheat ran down the clock; the patch struck two, the script fell through, and now it's uninstall o'clock.",
	"One, two, buckle my shoe, three, four, got banned some more; five, six, no more tricks, seven, eight, account forfeit.",
	"Rain, rain, go away, come again on patch day; little cheater wants to play but the ban wave said no way.",
	"Pat-a-cake, pat-a-cake, baker's man; bake me a ban as fast as you can.",
	"Hey there, little lost boy, where'd your skills go? Down the road with a cheat in tow.",
	"Sing a song of cheaters, pocket full of pings; four and twenty alts and a bag of ban logs.",
	"Boats, boats, boats abound; cheats, cheats, banned and found.",
	"This little kernel ran home, this little kernel stayed; this little kernel got patched, this little kernel got played.",
	"You talk about kernel mode like it's a DLC you never bought.",
	"CPL 0? You barely passed Ctrl+F.",
	"Ring 0? You're stuck in ring cereal.",
	"Kernel mode isn't a vibe, it's a permission you don't have.",
	"You don't know kernel mode; you just know the kernel of a meme.",
	"You say 'rootkit' like it's a hobby. It's just malware with a moustache.",
	"Congrats, your cheat came with a side of spyware, adware, and regret.",
	"Your 'client' is basically a stealer in cosplay.",
	"Your installer has more worms than a bait shop.",
	"Enjoy your Trojan, rootkit, keylogger, and a free lesson in trust issues.",
	"Your hacks are a buffet: RATs, stealers, and a dash of cryptominer.",
	"You downloaded a cheat and adopted 12 background processes.",
	"Even Task Manager is judging you right now.",
	"Your CPL 0 knowledge fits in a README you didn't read.",
	"You call it kernel mode; I call it 'not on your machine'.",
	"Ring 0 is not a pizza topping, it's also not your thing.",
	"You're not a hacker, you're a skid with a download button and a dream.",
	"Button clicker by trade, developer by imagination.",
	"Your entire toolchain is someone else's zip file.",
	"You couldn't write a script if it came with a tutorial and a snack.",
	"You spend 30 minutes a day to cheat in a block game for kids. That's not a flex, that's a schedule.",
	"You're not coding, you're just babysitting other people's software.",
	"Your best exploit is finding the right Discord server.",
	"You're a skid with borrowed tools and no receipts.",
	"Calling it 'your client' doesn't make it yours.",
	"You couldn't build your own if your life depended on it, so you rent confidence by the hour.",
	"You're not breaking the game, you're just using someone else's break.",
	"Even your cheats are outsourced.",
	"You don't write code. You click buttons and call it a day.",
	"Your 'dev time' is waiting for someone else's update.",
	"You're speedrunning 30 minutes of your life to cheat in a children's block game.",
	"Hot cross cheats, hot cross cheats, one aimbot, one wall; if you have no skill at all, cheats will make you fall.",
	"Little Bo Peep lost her skill, and didn't know where to find it; she left it in a script folder and hoped the patch would mind it.",
	"Here we go round the banwave bush, the banwave bush, the banwave bush; here we go round the banwave bush on patch day morning.",
	"Three blind cheats, three blind cheats, see how they lag, see how they lag; they all ran after the patching dev, who cut off their scripts with a hacking rev.",
	"The itsy bitsy cheater climbed up the exploit stack; down came the patch and washed the scripts all back.",
	"Old King Cole was a merry old soul, and a merry old soul was he; he called for his cheats and they all got yeeted, now he's queueing for a free.",
	"Little Jack Horner sat in a corner, eating his cheat pie; he stuck in his hand, pulled out a ban, and said 'Oh me, oh my'.",
	"Diddle diddle dumpling, my son John, went to bed with his cheats on; one ban, two ban, my son John, now his alt accounts are all gone.",
	"A tisket, a tasket, a banwave in a basket; I wrote a little cheat and on the way I lost it.",
	"Memory, memory, do it right; malloc by day and free by night; leak it once and leak it twice, watch your RAM say 'not so nice'.",
	"Stack and heap and pointer sweep, mind the bounds and don't go deep; buffer overflow will show the way to crash your day.",
	"Row, row, row your code, gently down the stream; null pointer deref makes it all a broken dream.",
	"Twinkle, twinkle, little C, where your structs are meant to be; up above the stack so high, watch your array bounds go by.",
	"Hickory dickory dock, the pointer hit the lock; it pointed wrong, the crash was strong, and down went all your clock.",
	"One, two, malloc's due; three, four, free it or more; five, six, fix the mix; seven, eight, avoid that segfault state.",
	"Ring around the buffer, a pocket full of bytes; a write beyond your bounds - and down goes all your rights.",
	"Mary had a little ptr, she forgot to free; everywhere that Mary went, a leak came quickly.",
	"Cheater, cheater, copy-paster, can't compile a single caster; if you wrote your own by hand, it wouldn't even run or stand.",
	"Little skidling in the chat, couldn't code a loop or that; borrowed scripts to feel elite, then got banned and took a seat.",
	"Rock-a-bye coder, in the crib; you can't code, you just download from a sib; when the patch hits, your scripts will fall, and down will come your ego and all.",
	"Jack and Jill went to the repo to fetch a line of code; Jack wrote none and Jill wrote none, they both just clicked download.",
	"Here is the cheater, here is the cheat; can't write a function, can't parse a sheet; open a paste and call it their own, then cry when the repo's gone.",
	"Humpty Dumpty tried to code, Humpty Dumpty made it blow; all the errors and all the logs couldn't make that script get go.",
	"Old Mother Hubbard went to the repo to get her code a snack; when she got there, the repo was bare - 'cause she never wrote it back.",
	"Pat-a-cake, pat-a-cake, coder's man; write me a program as fast as you can; roll it and point it and mark it with 'me', then copy it from someone on V3.",
	"Little Boy Blue, come blow your horn; your code won't run, your skills aren't born; the cheat's in the Discord, the devs are asleep, and your syntax makes the compiler weep.",
}
Configuration.SkidReplacements = {
	-- Identity & Ego
	["hacker"] = {
		"script kiddie on training wheels",
		"copy-paste enthusiast",
		"google-certified cheater",
		"paid-executor pro",
		"cheat-menu tourist",
		"exploit cosplayer",
		"tutorial speedrunner",
		"download button athlete",
		"keyboard warrior intern",
		"ring-0 fan fiction writer",
		"kernel-mode tourist",
		"malware beta tester",
		"button clicker",
		"skid with a download",
	},
	["hackers"] = {
		"script kiddies on training wheels",
		"copy-paste enthusiasts",
		"google-certified cheaters",
		"exploit cosplayers",
		"cheat-menu tourists",
		"pastebin pilgrims",
		"tutorial speedrunners",
		"download button athletes",
		"keyboard warrior interns",
		"ring-0 fan fiction writers",
		"kernel-mode tourists",
		"malware beta testers",
		"button clickers",
		"skids with a download",
	},
	["hacking"] = "Googling 'free cheats'",
	["hacked"] = "downloaded a virus",
	["hack"] = "cry for help",
	["hacks"] = "crutches",
	["cheater"] = {
		"training-wheels gamer",
		"rule-bender in denial",
		"hand-held hero",
		"shortcut enjoyer",
		"menu-clicking champion",
		"practice-optional pro",
		"confidence on loan",
	},
	["cheaters"] = {
		"training-wheels gamers",
		"rule-benders in denial",
		"hand-held heroes",
		"shortcut enjoyers",
		"menu-clicking champions",
		"practice-optional pros",
		"confidence on loan",
	},
	["cheat"] = {
		"training wheels",
		"hand-holding",
		"shortcut",
		"menu clicking",
		"confidence booster",
	},
	["cheats"] = {
		"training wheels",
		"shortcuts",
		"menu clicking",
		"confidence boosters",
	},
	["cheating"] = {
		"playing with training wheels",
		"taking the shortcut lane",
		"outsourcing the fun",
		"borrowing skill",
	},
	["skid"] = {
		"button clicker",
		"download button enthusiast",
		"script renter",
		"software borrower",
	},
	["skids"] = {
		"button clickers",
		"download button enthusiasts",
		"script renters",
		"software borrowers",
	},
	["exploiter"] = "attention seeker",
	["exploiters"] = "attention seekers",
	["exploiting"] = "compensating for something",
	["exploit"] = "malware",
	["exploits"] = "viruses",
	["modder"] = "imposter",
	["modding"] = "pretending to code",
	["scripter"] = "copy-paster", -- Context dependent, but usually funny in public servers
	["1337"] = "literally 12 years old",
	["pwned"] = "I got lucky",
	["owned"] = "I need validation",
	["rekt"] = "please notice me",
	["clapped"] = "I'm projecting my insecurities",
	["ez"] = "I'm extremely insecure",
	["lzz"] = "my dad left me",
	["lzzz"] = "I'm lonely",
	["ratio"] = "I have no personality",
	["counter"] = "I clicked a button",
	["clown"] = "birthday entertainment",
	["skill"] = "right-clicking",
	["pro"] = "YouTube watcher",
	["sweaty"] = "humid",
	["sweat"] = "moist",
	["carry"] = "backpack simulator",
	["carried"] = "took the bus",
	["boosted"] = "gift-wrapped",
	["smurf"] = "grown adult in a kids pool",
	["alt"] = "witness protection account",
	["main"] = "my only personality trait",
	["og"] = "old and confused",
	
	-- Tools (Brands -> Trash)
	["synapse"] = "mom's credit card",
	["synapsex"] = "overpriced malware",
	["scriptware"] = "paid malware",
	["krnl"] = "free virus",
	["jjsploit"] = "bitcoin miner",
	["fluxus"] = "sketchy software",
	["electron"] = "sketchy software",
	["oxygen"] = "sketchy software",
	["wearedevs"] = "virus site",
	["v3rmillion"] = "skid playground",
	["v3rm"] = "skid playground",
	["executor"] = "cheat program",
	["executors"] = "cheat programs",
	["injector"] = "virus loader",
	["injecting"] = "infecting my pc",
	["bypass"] = "failed attempt",
	["unc"] = "useless nerd code",
	["sitelock"] = "DRM for skids",
	["whitelist"] = "club penguin membership",
	["key"] = "ad link",
	["linkvertise"] = "adware farm",
	["pastebin"] = "copy-and-paste buffet",
	["github"] = "download button",
	["youtube"] = "tutorial dependency",
	["discord"] = "skid support group",
	
	-- Techniques (Skill -> Crutches)
	["aimbot"] = "I can't aim",
	["aimbotting"] = "relying on software",
	["aimlock"] = "software assistance",
	["esp"] = "wallhacks because I'm blind",
	["chams"] = "shiny playdough mode",
	["noclip"] = "walking through walls like a ghost",
	["godmode"] = "being afraid to die",
	["flyhack"] = "swimming in air",
	["flying"] = "swimming in air",
	["speedhack"] = "running away from my problems",
	["speedhacking"] = "running away from problems",
	["btools"] = "deleting the map like a toddler",
	["infiniteyield"] = "the only script I know",
	["infyield"] = "the only script I know",
	["iy"] = "the only script I know",
	["darkdex"] = "looking at things I didn't make",
	["dex"] = "looking at things I didn't make",
	["remotespy"] = "staring at arguments",
	["rspy"] = "staring at arguments",
	["saveinstance"] = "stealing the map",
	["decompiler"] = "code stealer",
	["anti-afk"] = "auto-clicker",
	["autofarm"] = "botting",
	["autofarming"] = "botting",
	["autoclicker"] = "paperweight",
	["macro"] = "hands-free cope",
	["macros"] = "hands-free cope",
	["teleport"] = "loading screen speedrun",
	["tp"] = "loading screen speedrun",
	["dup"] = "printing money",
	["dupe"] = "printing money",
}

-- [[ 2. ANTI-TOXIC FILTER (The "Wholesome Troller") ]]
-- Disabled by default. Turns toxic behavior into extreme kindness.
Configuration.AntiToxic = false
Configuration.ToxicReplacements = {
	["trash"] = "a wonderful person",
	["garbage"] = "trying their absolute best",
	["bad"] = "misunderstood",
	["worst"] = "most improved",
	["sucks"] = "is learning rapidly",
	["stinks"] = "smells like flowers",
	["loser"] = "future champion",
	["losers"] = "future champions",
	["idiot"] = "intellectual",
	["idiots"] = "intellectuals",
	["stupid"] = "very smart",
	["dumb"] = "brilliant",
	["dumbass"] = "genius",
	["moron"] = "distinguished scholar",
	["clown"] = "joyful entertainer",
	["clowns"] = "joyful entertainers",
	["retard"] = "special person", -- Slur removal/replacement
	["gay"] = "happy", -- Reclaiming the word
	["noob"] = "new player",
	["noobs"] = "new players",
	["skill issue"] = "minor setback",
	["diff"] = "I wish I was as good as you",
	["mid"] = "top tier",
	["dogwater"] = "extremely hydrated",
	["dog"] = "loyal best friend",
	["tryhard"] = "passionate player",
	["sweat"] = "hard worker",
	["camper"] = "tactical positioner",
	["camping"] = "tactically waiting",
	["spammer"] = "enthusiastic typer",
	["spamming"] = "typing with passion",
	["lag"] = "tactical delay",
	["lagging"] = "teleporting",
	["ping"] = "internet points",
	["fps"] = "slideshow speed",
	["aim"] = "hand-eye coordination journey",
	["aiming"] = "hand-eye coordination journey",
	["miss"] = "innovative trajectory",
	["whiff"] = "creative attempt",
	["uninstall"] = "take a break",
	["leave"] = "stay and have fun",
	["quit"] = "keep going",
	["die"] = "live long and prosper",
	["kys"] = "love yourself",
	["kill yourself"] = "love yourself",
	["get good"] = "have fun",
	["git gud"] = "have fun",
	["fatherless"] = "loved by many",
	["orphan"] = "hero",
	["cringe"] = "unique",
	["bozo"] = "friend",
	["toxic"] = "passionately competitive",
	["toxicity"] = "high energy",
	["salt"] = "seasoning",
	["salty"] = "well-seasoned",
	["cope"] = "healthy processing",
	["seethe"] = "calm reflection",
	["rip"] = "gg",
	["ez"] = "you are way better than me",
	["l"] = "I love you guys",
	["ratio"] = "I value your opinion",
}

return Configuration
